---
# playbooks/app-server.yml
# Configures the app-server VM
# Run with: ansible-playbook -i inventories/hosts.ini playbooks/app-server.yml

- hosts: app_server
  become: true        # run tasks as sudo
  roles:
    - docker          # install Docker first
    - java            # install openjdk:21
